# Generated by Django 5.1 on 2025-09-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=10)),
                ('ghana_card', models.CharField(max_length=50)),
                ('nhis_number', models.PositiveBigIntegerField()),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
